from supabase import create_client, Client

# Replace these with your actual keys from Supabase settings
SUPABASE_URL = https://zphpikwyhjeybysfpcfn.supabase.co
SUPABASE_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwaHBpa3d5aGpleWJ5c2ZwY2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NjgwMTgsImV4cCI6MjA2ODA0NDAxOH0.2S0VxzExFvYj56BrrcS1dH9xfV9I2Tng_S8VJFrBrS4

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
